### ISSUE TITLE
Mixing core and compatibility profile (Iris support)

### ISSUE THREAD

**Issue by IMS212** [HaringProGit/Revelation#3]
There are currently three reasons this shader does not load on Iris.

1. `#include` is case specific, and it is wrong for Utility.glsl and ScreenSpaceRaytracer.glsl.
2. You are marking your shaders as compatibility profile, but using the core profile design. This causes Iris to send nothing as the position, making everything invisible. This can easily be fixed by replacing all `#version 450 compatibility` with `#version 450 core`.
3. There is a bug in Iris's core patcher. This will be fixed in the next release

**Comment by HaringProGit** [comment]
Thank you for your attention and recognition, I've seen the bugs in my pack and they'll be fixed soon.

**Comment by HaringProGit** [comment]
Well they've been fixed. Just look forward to the next release version of Iris.
