### ISSUE TITLE
When the time is between 23150 and 23250, sunlight will appear in the opposite direction first.

### ISSUE THREAD

**Issue by MoAoXnX** [HaringProGit/Revelation#5]
When the time is between 23150 and 23250, sunlight will appear in the opposite direction first.
time set 23200之前的阳光光照位置是反的，23200的一瞬间变成正常方向。
![屏幕截图(4079)](https://github.com/user-attachments/assets/c86cd2aa-195c-4a43-8e0f-ff0a63956d60)
![屏幕截图(4078)](https://github.com/user-attachments/assets/a93c0284-1dea-4d94-bcac-39a80bafb087)

**Comment by HaringProGit** [comment]
ok, it'll be fixed in the next update
