### ISSUE TITLE
启用RAYTRACED_REFRACTION的时候水边出现奇怪的错误折射

### ISSUE THREAD

**Issue by FlywithYou1** [HaringProGit/Revelation#6]
开启光线追踪折射的情况下，面对水面的时候其它方块上面会出现类似水的方块，此情况在人物移动时尤为明显
![2024-09-24_21 51 51](https://github.com/user-attachments/assets/ead5ec55-48d6-4b10-827f-fedc79d47978)

**Comment by lty668** [comment]
![2024-10-01_15 48 25](https://github.com/user-attachments/assets/b99ee3da-9c2d-4cfc-a2f3-4336a99f6d78)

**Comment by HaringProGit** [comment]
屏幕空间追踪的限制，无法解决
