### ISSUE TITLE
使用iris1.8时开启Environment-Transparent-Translucent_LIGHTING会导致光影无法加载

### ISSUE THREAD

**Issue by FlywithYou1** [HaringProGit/Revelation#9]
![image](https://github.com/user-attachments/assets/58798d81-da66-43d4-8c8d-37989c1ee05a)
错误代码如下
terrain_translucent.fsh: terrain_translucent.fsh: 0(770) : error C1503: undefined variable "worldDistSquared"

**Comment by OrzMiku** [comment]
emm，这个着色器有“terrain_translucent.fsh”这个文件吗？

**Comment by HaringProGit** [comment]
已知，下次更新中会被修复
